# Generated by Django 3.2.9 on 2021-12-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rememberwhenapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='is_Approved',
            new_name='is_approved',
        ),
    ]
