# Generated by Django 3.2.10 on 2022-01-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rememberwhenapi', '0004_fact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='rememberwhenapi.year'),
        ),
    ]
